title: MNNIT Computer Coding Club
description: This repository contains the codes, support links and other relevant materials for every class under Computer Club, MNNIT Allahabad.
image: sample_image.png
type: website

url: https://cc-mnnit.github.io

theme: jekyll-theme-hacker
